# Generated by Django 3.0.5 on 2020-07-26 22:55

import api.helpers
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_id', models.CharField(max_length=100, unique=True)),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('xp', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('xp_to_lvlup', models.IntegerField(default=1515, validators=[django.core.validators.MinValueValidator(1515)])),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(blank=True, max_length=6, validators=[api.helpers.validate_type])),
                ('difficulty', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('xp', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)])),
                ('parent_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.User')),
            ],
        ),
    ]
